#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

PYTHON_VERSION=$(${PREFIX}python -V)
set +e
echo $PYTHON_VERSION | grep "3.6" > /dev/null
if [ $? -eq 0 ]; then
    # Skipped for now.
    # See: https://github.com/encode/httpcore/pull/205
    exit 0
fi
set -e

${PREFIX}coverage report --show-missing --skip-covered --fail-under=93
